config/routes.rb
TestJs::Application.routes.draw do
  resources :commentaries

  devise_for :users

  resources :users

  resources :categories do
    put :moderation_comment, on: :member
    put :moderation_map, on: :member
  end

  resources :maps

  resources :roles

   root :to => 'Maps#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :title, :category_id, :coord, :more, :image, :reach

  validates :title, :category_id, :coord, :more, :reach, presence: true
  validates :title, :length => {in: 6..30}
  validates :more, :reach, :length => {in: 40..120}
  validates :coord, format: { with: /\A[0-9,.]+\z/ }

  has_many :commentaries
  belongs_to :category
  belongs_to :user

  scope :moderation, ->(state) { where("moderation = ?", state) }
  mount_uploader :image, ImageUploader

  def self.unload_place(gon)
    gon.map_id = []
    gon.map_coord = []
    gon.map_title = []
    gon.map_img = []
    gon.str = []

    for num in (1..6)
      gon.map_coord[num-1] = [num]
      gon.map_img[num-1] = [num]
      gon.map_title[num-1] = [num]
      gon.map_id[num-1] = [num]
      i = 0
      j = 0
      Map.where('moderation = 0 and category_id = ?', num).each do |m|
        gon.str = m.coord.split(',')
        gon.map_coord[num-1][i] =  gon.str[0].to_f
        gon.map_coord[num-1][i+1] =  gon.str[1].to_f
        gon.map_title[num-1][j] = m.title
        gon.map_img[num-1][j] = m.image_url   ### img_url
        gon.map_id[num-1][j] = m.id
        i = i + 2
        j = j + 1
      end
    end
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  load_and_authorize_resource :except => [:index, :show]
  before_filter :find_map, :only => [:destroy, :update, :edit, :show]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.moderation(0)

    if params[:point]
      point = params[:point].to_i
      @point = Map.find(point)
      @commentaries = Commentary.find_by_map_id(point)
      @user = User.find_by_id(params[:user].to_i)
    else
      @map = Map.new
      Map.unload_place(gon)
      user_present?()
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show

    respond_to do |format|
      format.html # _show.html.slim
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.slim
    end
  end

  # GET /maps/1/edit
  def edit

  end

  # POST /maps
  # POST /maps.json
  def create
    @map = current_user.maps.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to root_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to categories_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
    end
  end

  private
  def user_present?
    if current_user.present?
      @user = User.find(current_user)
      @commentary = current_user.commentaries.new
      @count_map = Map.moderation(1).count
      @count_commentary = Commentary.moderation(1).count
    end
  end

  def find_map
    @map = Map.find(params[:id].to_i)
  end

end

app/helpers/maps_helper.rb
module MapsHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def img_class(category_id)
    case category_id
      when 1
        @img_class = "myDostopCollection"
      when 2
        @img_class = "myIntCollection"
      when 3
        @img_class = ""
      when 4
        @img_class = "myArtCollection"
      when 5
        @img_class = "myMeetCollection"
      when 6
        @img_class = "myBigCollection"
    end
  end

  def avatar?(o,w,h)
    if o.avatar?
      raw "<img src=\"#{o.avatar}\" width=\"#{w}\" height=\"#{h}\" alt=\"Avatar\">"
    else
      raw "<img src=\"/assets/noavatar.png\" width=\"#{w}\" height=\"#{h}\" alt=\"No avatar\">"
    end
  end

end

app/views/maps/_comment.html.slim
javascript:
  function profile(user,map) {
      $.ajax({
        dataType: "script",
        url: '/?user=' + user + '&point=' + map,
        success: function(html) {
          $("fieldset#form_profile").show();
        }
      });
  }

div#scroll_comment
  fieldset#form_profile
  br
  - @commentaries.order("created_at desc").each do |commentary|
    div.ava-area_comment
      = avatar?(commentary.user,60,60)
    div.author_comment
      span.hov style="font-weight:bold"
        - if current_user.nil?
          = commentary.user.name
        - else
          span onClick="javascript:profile('#{commentary.user.id}','#{commentary.map_id}');"
            = commentary.user.name
      br
      span style="font-size:9px"
        = commentary.created_at
      br
      div style="margin: 0px 0px 0px 7px;"
        = commentary.description
    div style="font-size:8px;"
      - if can? :destroy, commentary
        br
        = link_to 'Destroy', commentary, :confirm => 'Are you sure?', :method => :delete, :remote => :true
    br
    hr

app/views/maps/_form.html.slim
= form_for(@map, :html => {:target => 'upload_target'}) do |f|
  div
    = f.text_field :title, placeholder: "Название.."

  = f.hidden_field :coord
  div
    = f.text_area :more, :rows => "4", placeholder: "Описание.."
  div
    = f.text_area :reach, :rows => "4", placeholder: "Как добраться.."
  div
    = f.select :category_id, ['Выбрать категорию'] + Category.all.collect{|s| [s.title, s.id]}
  br
  div
    | Фото:
    | &nbsp;
    = f.file_field :image, placeholder: "Фото"
  br
  div#point
    = f.submit 'Добавить отметку', class: "add_point_submit"


iframe id="upload_target" name="upload_target" style="display: none"

app/views/maps/_menu_collection.html.slim
div.layer4
  div.chkDiv style="position: absolute; top: 5%; left:2%"
    input name="myDostopCollection" value="1" tabindex="1" type="checkbox" id="myDostopCollection"
      | &nbsp;
      label.lab for="myDostopCollection"
        | Достопримечательности

  div class="chkDiv" style="position: absolute; top: 35%; left:2%"
    input name="Filter" value="2" tabindex="2" type="checkbox" id="myIntCollection"
      | &nbsp;
      label class="lab" for="myIntCollection"
        | Интересные места

  div class="chkDiv" style="position: absolute; top: 65%; left:2%"
    input name="Filter" value="3" tabindex="3" type="checkbox" id="chk3"
      | &nbsp;
      label class="lab" for="chk3"
        | Ожидаемое

div.layer5
  div class="chkDiv" style="position: absolute; top: 5%; left:2%"
    input name="Filter" value="4" tabindex="4" type="checkbox" id="myArtCollection"
      | &nbsp;
      label class="lab" for="myArtCollection"
        | Арт

  div class="chkDiv" style="position: absolute; top: 35%; left:2%"
    input name="Filter" value="5" tabindex="5" type="checkbox" id="myMeetCollection"
      | &nbsp;
      label class="lab" for="myMeetCollection"
        | Встречи

  div class="chkDiv" style="position: absolute; top: 65%; left:2%"
    input name="Filter" value="6" tabindex="6" type="checkbox" id="myBigCollection"
      | &nbsp;
      label class="lab" for="myBigCollection"
        | Хочу больше!

app/views/maps/_more.html.slim
= @point.more

app/views/maps/_reach.html.slim
= @point.reach

app/views/maps/_sign_in.html.slim
div#signin_menu_align
  = form_for(resource, as: resource_name, url: user_session_path) do |f|
    = f.email_field :email, placeholder: "Ваш email.."

    = f.password_field :password, placeholder: "Ваш пароль.."

    br
    br
    = f.submit 'Войти', id: "signin_submit"
    br
    br
    div
      img#oID_B style="width:5%;" src="/assets/oID_B.png"
      | &nbsp;
      img#oID_T style="width:5%;" src="/assets/oID_T.png"
      | &nbsp;
      img#oID_F style="width:5%;" src="/assets/oID_F.png"
      | &nbsp;
      img#oID_M style="width:5%;" src="/assets/oID_M.png"

    br
    span id="reg_button" style="cursor:pointer;" class="reg-btn"
      | Или зарегистрироваться!

app/views/maps/_sign_up.html.slim
div#signin_menu_align
  = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|

    = f.email_field :email, :autofocus => true, placeholder: "Ваш email.."

    = f.text_field :name, placeholder: "Ваше имя.."

    = f.password_field :password, placeholder: "Пароль.."

    = f.password_field :password_confirmation, placeholder: "Повторите пароль.."
    br
    = f.submit "Зарегистрироваться", :id => "reg_submit"

app/views/maps/_top_admin.html.slim
div.ava-area
  = avatar?(current_user,100,100)

fieldset#add_comment
  = render ("commentaries/form")

fieldset#prof_menu
  = render ("users/form")

fieldset#add_point
  = render ("form")

div.menu
  div style="position: absolute; top: 0%; left:2%"
    div.name-btn
      = current_user.name
  div style="position: absolute; top: 25%; left:2%"
    div.user-btn
      div.metka-btn
        | Добавить точку

  div style="position: absolute; top: 45%; left:2%"
    div.user-btn
      = link_to 'События', categories_path, id: "sign_out_text"
      | &nbsp;
      = @count_map + @count_commentary

  div style="position: absolute; top: 65%; left:2%"
    div.user-btn
      = link_to 'Админка', categories_path, id: "sign_out_text"

  div#profile style="position: absolute; top: 85%; left:2%"
    div.user-btn
      | Мой профиль

= render ('maps/menu_collection')

div#sign_out
  = link_to 'Выйти', destroy_user_session_path, :method => :delete, id: "sign_out_text"

app/views/maps/_top_user.html.slim
div.ava-area
  = avatar?(current_user,100,100)

fieldset#add_comment
  = render ("commentaries/form")

fieldset#prof_menu
  = render ("users/form")

fieldset#add_point
  = render ("form")

div.menu
  div style="position: absolute; top: 1%; left:2%"
    div.name-btn
      = current_user.name
  div style="position: absolute; top: 55%; left:2%"
    div.user-btn
      div.metka-btn
        | Добавить точку
  div#profile style="position: absolute; top: 80%; left:2%"
    div.user-btn
      | Мой профиль

= render ('maps/menu_collection')

div#sign_out
  = link_to 'Выйти', destroy_user_session_path, :method => :delete, id: "sign_out_text"

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.slim
div.top
  - if user_signed_in?
    - if (current_user.role? :administrator)
      = render ('top_admin')
    - else
      = render ('top_user')
  - else
    = render ('top_guest')

div.mid
  div.rad-btn
    div.rad-btn-text
      span Задать область
    div.rad-btn-slide-text
  div.area-btn
    div.area-btn-text
      span.checkall
        | Отметить /
      span.uncheckall
        | Снять Все
    div.area-btn-slide-text
  div.search-btn
    form.test
      input class="input-xlarge search-query" id="search" name="Search" value="" placeholder="Задать адрес.." title="search" tabindex="9" type="text"
      div class="search-btn-icon-right"

fieldset#form_comment

fieldset#form_howtoreach

fieldset#form_more

div.cont
  div class="layer1"
    div.hello
      | Все, что нужно увидеть и посетить в Самаре!
      hr style="margin: 5% 5% 0% 5%;"

    /каждой фотографии задаем class на принадлежность к коллекции и id для связи фото - метка. фотографии и инфу по ним будем храним в бд
    /id - номер записи в таблице, т.к. добавление в бд метки и фотографии происходит одновременно(и их количество =), то id метки = id фото
    div.gal
      /1	Достопримечательности
      /2	Интересные места
      /3	Ожидаемое
      /4	Арт
      /5	Встречи
      /6	Хочу Больше!

      - @maps.find_each do |map|
        a
          img style='width:45%;' src='#{map.image_url}' class='#{img_class(map.category_id)}' id='#{map.id}' title='#{map.title}' alt='#{map.title}'

  div id="map" class="layer2"
    div class="layer3"
      | ... 2013 ...

app/views/maps/index.js.erb
$("#form_comment").html("<%= j render(:partial => 'maps/comment') %>");
$("#form_howtoreach").html("<%= j render(:partial => 'maps/reach') %>");
$("#form_more").html("<%= j render(:partial => 'maps/more') %>");
$("#form_profile").html("<%= j render(:partial => 'users/show') %>");

app/views/maps/show.html.slim
br
b Название: &nbsp;
= @map.title
br
b Подробнее: &nbsp;
= @map.more
br
b Как доехать: &nbsp;
= @map.reach
br
b Координаты: &nbsp;
= @map.coord
br
b Фото: &nbsp;
= image_tag(@map.image)
/- @map.each do |m|
  = m.title
  = m.more
  = m.hotoreach
  /= m.img


br
  br
= link_to 'Edit', edit_map_path(@map)
| &nbsp; | &nbsp;
= link_to 'Back', :back