config/routes.rb
TestJs::Application.routes.draw do
  resources :commentaries

  devise_for :users

  resources :users

  resources :categories do
    put :moderation_comment, on: :member
    put :moderation_map, on: :member
  end

  resources :maps

  resources :roles

   root :to => 'Maps#index'

end

app/models/commentary.rb
class Commentary < ActiveRecord::Base
  attr_accessible :description, :map_id, :user_id

  validates :description, :user_id, presence: true
  validates :description, :length => {in:2..300}
#  validates :description, format: { with: /\A[а-яА-ЯёЁa-zA-Z0-9.,+-:_]+\z/}

  belongs_to :user
  belongs_to :map

  scope :moderation, ->(state) { where("moderation = ?", state) }
  scope :find_by_map_id, ->(id) { where("map_id = ?", id) }
end

app/controllers/commentaries_controller.rb
class CommentariesController < ApplicationController

  load_and_authorize_resource :except => [:index, :show]
  before_filter :find_comment, :only => [:destroy, :update, :edit, :show]

  # GET /commentaries
  # GET /commentaries.json
  def index
    @commentaries = Commentary.find_by_map_id(params[:id].to_i)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /commentaries/1
  # GET /commentaries/1.json
  def show

    respond_to do |format|
      format.html # _show.html.slim
    end
  end

  # GET /commentaries/new
  # GET /commentaries/new.json
  def new
    @commentary = Commentary.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /commentaries/1/edit
  def edit

  end

  # POST /commentaries
  # POST /commentaries.json
  def create
    @commentaries = Commentary.find_by_map_id(params[:commentary][:map_id].to_i)
    @commentary = current_user.commentaries.new(params[:commentary])

    respond_to do |format|
      if @commentary.save
        format.html { redirect_to @commentary, notice: 'Commentary was successfully created.' }
        format.js {}
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /commentaries/1
  # PUT /commentaries/1.json
  def update

    respond_to do |format|
      if @commentary.update_attributes(params[:commentary])
        format.html { redirect_to root_path }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /commentaries/1
  # DELETE /commentaries/1.json
  def destroy
    @commentary.destroy

    respond_to do |format|
      format.js
    end
  end

  private
  def find_comment
    @commentary = Commentary.find(params[:id].to_i)
  end

end

app/helpers/commentaries_helper.rb
module CommentariesHelper
end

app/views/commentaries/_form.html.slim
= form_for @commentary, :remote => true do |f|
  /- if @commentary.errors.any?
    #error_explanation
      h2 = "#{pluralize(@commentary.errors.count, "error")} prohibited this commentary from being saved:"
      ul
        - @commentary.errors.full_messages.each do |message|
          li = message

  /.field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.text_area :description, placeholder: "Ваш отзыв.."
  .field
    = f.hidden_field :map_id

  div style="text-align:center;"
    = f.submit 'Отправить', id: "add_comment_submit"

app/views/commentaries/create.js.erb
$("#form_comment").html("<%= j render(:partial => 'maps/comment') %>");
$('fieldset#add_comment').toggle();

app/views/commentaries/edit.html.slim
h1 Editing commentary

== render 'form'

/= link_to 'Show', @commentary
/'|
/= link_to 'Back', commentaries_path

app/views/commentaries/index.html.slim
h1 Listing commentaries

/- @comment.each do |c|
  = c.user_id
  br
  = c.description
  br
  = c.map_id
  br
  br


table
  tr
    th User
    th Description
    th Map
    th
    th
    th

  - @commentaries.each do |commentary|
    tr
      td = commentary.user_id
      td = commentary.description
      td = commentary.map_id
      td = link_to 'Show', commentary
      td = link_to 'Edit', edit_commentary_path(commentary)
      td = link_to 'Destroy', commentary, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Commentary', new_commentary_path

app/views/commentaries/new.html.slim
h1 New commentary

== render 'form'

= link_to 'Back', commentaries_path

app/views/commentaries/show.html.slim
p#notice = notice

p
  strong User:
  = @commentary.user_id
p
  strong Description:
  = @commentary.description
p
  strong Map:
  = @commentary.map_id

= link_to 'Edit', edit_commentary_path(@commentary)
'|
= link_to 'Back', commentaries_path