config/routes.rb
TestJs::Application.routes.draw do
  resources :commentaries

  devise_for :users

  resources :users

  resources :categories do
    put :moderation_comment, on: :member
    put :moderation_map, on: :member
  end

  resources :maps

  resources :roles

   root :to => 'Maps#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :id

  validates :title, presence: true
  validates :title, :length => {in:4..12}

  has_many :maps

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource
  before_filter :find_cat, :only => [:destroy, :update, :edit, :show]

  # GET /categories
  # GET /categories.json
  def index
    @maps = Map.select("id, title, category_id, user_id, image")
    @categories = Category.select("id, title")
    @roles = Role.select("id, name")
    @users = User.select("ID,Name,Email")

    @maps_mod = Map.moderation(1).select("id, created_at, title, user_id")
    @comment_mod = Commentary.moderation(1)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show

    respond_to do |format|
      format.html # _show.html.slim
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /categories/1/edit
  def edit

  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  def moderation_comment
    @comm = Commentary.find(params[:id])

    respond_to do |format|
      @comm.update_attribute(:moderation, 0)
      format.js
    end
  end

  def moderation_map
    @map = Map.find(params[:id])

    respond_to do |format|
      @map.update_attribute(:moderation, 0)
      format.js
    end
  end

  private
  def find_cat
    @category = Category.find(params[:id].to_i)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.slim
table
  tr
    th ID
    th Title
    th
    th
    th

  - @categories.each do |category|
    tr
      td = category.id
      td = category.title
      - if can? :update, category
        td = link_to 'Edit', edit_category_path(category)
      - if can? :destroy, category
        td = link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete
= link_to 'New Category', new_category_path

app/views/categories/_events.html.slim
table
  tr
    th Дата
    th Название
    th Пользователь
    th
    th

  - @maps_mod.each do |map|
    tr
      td = map.created_at
      td
        b = link_to map.title, map_path(map)
      td = map.user.name
      td
        = link_to 'Одобрить', moderation_map_category_path(map), :remote => :true, :method => :put, :class => "maps"
      td
        - if can? :destroy, map
          = link_to 'Удалить', map, :confirm => 'Are you sure?', :method => :delete, :remote => :true

br

table
  tr
    th Дата
    th Метка
    th Пользователь
    th Комментарий
    th
    th

  - @comment_mod.each do |comment|
    tr
      td = comment.created_at
      td
        = Map.where('id = ?', comment.map_id).pluck(:title)
      td = comment.user.name
      td
        b = comment.description
      td
        = link_to 'Одобрить', moderation_comment_category_path(comment), :remote => :true, :method => :put, :class => "comment"
      td
        - if can? :destroy, comment
          = link_to 'Удалить', comment, :confirm => 'Are you sure?', :method => :delete, :remote => :true

br

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit 'Save'

app/views/categories/_maps.html.slim
table
  tr
    th ID
    th Title
    th Category
    th User_id
    th Image
    th
    th
    th

  - @maps.each do |map|
    tr
      td = map.id
      td = map.title
      td = map.category_id
      td = map.user_id
      td
        = image_tag(map.image)
      td = link_to 'Show', map
      - if can? :update, map
        td = link_to 'Edit', edit_map_path(map)
      - if can? :destroy, map
        td = link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete

br

app/views/categories/_roles.html.slim
table
  tr
    th ID
    th Name
    th
    th

  - @roles.each do |role|
    tr
      td = role.id
      td = role.name
      - if can? :update, role
        td = link_to 'Edit', edit_role_path(role)
      - if can? :destroy, role
        td = link_to 'Destroy', role, :confirm => "Are you sure?", :method => :delete
= link_to 'New Role', new_role_path
br

app/views/categories/_users.html.slim
table
  tr
    th ID
    th Name
    th Email
    th Access
    th
    th

  - @users.each do |user|
    tr
      td = user.id
      td = user.name
      td = user.email
      td = user.role_ids
      - if can? :update, user
        td = link_to 'Edit', edit_user_path(user)
      - if can? :destroy, user
        td = link_to 'Destroy', user, :confirm => "Are you sure?", :method => :delete
br

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
div.admin_title
  = link_to 'На главную', root_path
  br
  br
  a href="#" class="fadeNext"
    | События
    br
  div class="fader"
    = render ('events')
  br
  a href="#" class="fadeNext"
    | Пользователи
    br
  div class="fader"
    = render ('users')
  br
  a href="#" class="fadeNext"
    | Роли
    br
  div class="fader"
    = render ('roles')
  br
  a href="#" class="fadeNext"
    | Категории
    br
  div class="fader"
    = render ('categories')
  br
  a href="#" class="fadeNext"
    | Метки
    br
  div class="fader"
    = render ('maps')

app/views/categories/moderation_comment.js.erb
//alert(gon.comm);
$(this).hide();

app/views/categories/moderation_map.js.erb
$(this).hide();

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Title:
  = @category.title

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path